---
  # Pull from github #
  ####################
  - name: install git
    apt:
      pkg: git
      update_cache: yes
      state: latest
    sudo: yes
    register: gitInstallResult
    ignore_errors: True

  - name: get repo from github
    git:
      repo: https://github.com/DominicSina/VaultServer.git
      dest: /opt/VaultServer
      version: storingCertificates
      update: yes
      force: yes
    register: gitPullResult
    ignore_errors: True
    sudo: yes

  # Handle certificate creation #
  ###############################
  - name: make sure secrets folder exists
    file:
      state: directory
      path: /opt/VaultServer/Vault/Secrets
    register: secretsGenResult
    sudo: yes

  - name: create ca
    command: openssl req -newkey rsa:2048 -keyout /opt/VaultServer/Vault/Secrets/privkey.pem -days 3650 -x509 -nodes -out /opt/VaultServer/Vault/Secrets/root.cer -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=DevCA"
    when: secretsGenResult|changed
    sudo: yes

  - name: create csr
    command: openssl req -newkey rsa:1024 -nodes -out /opt/VaultServer/Vault/Secrets/vault.csr -keyout /opt/VaultServer/Vault/Secrets/vault.key -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=DevCA"
    when: secretsGenResult|changed
    sudo: yes

  - name: create crt
    command: openssl ca -batch -config /opt/VaultServer/Vault/TLS/vault-ca.conf -notext -in /opt/VaultServer/Vault/Secrets/vault.csr -out /opt/VaultServer/Vault/Secrets/vault.crt
    when: secretsGenResult|changed
    sudo: yes

  - name: Let git assume TLS files are unchanged
    command: git update-index --assume-unchanged Vault/TLS/{{ item }}
    when: secretsGenResult|changed
    with_items:
    - certindex
    - serialfile
    args:
      chdir: /opt/VaultServer
    sudo: yes

  # Some stuff to help with local debugging #
  ###########################################
  # Only available to a registered user, not useful for following ansible shell module.
  # Still nice to have for local debugging on the target machines.
  - name: add vault binary to PATH in bashrc 
    lineinfile:
      dest: ~/.bashrc
      line: 'export PATH="$PATH:/opt/VaultServer/Vault" # Adds vault binary to PATH'

  # Similar to task above. Specifies to access local vault server through http using bash.
  - name: add local vault server address in bashrc
    lineinfile:
      dest: ~/.bashrc
      line: 'export VAULT_ADDR="http://127.0.0.1:8200" # Adds local vault server address to bash'

  # Configure run options and start vault service #
  #################################################
  # Memlock is needed for vault in linux systems. Vault needs memlock capabilites when
  # nonencrypted swaps are performed https://www.vaultproject.io/docs/configuration/index.html
  - capabilities: 
      path: /opt/VaultServer/Vault/vault
      capability: cap_ipc_lock=+ep
      state: present
    sudo: yes

  - name: copy service file
    command: cp /opt/VaultServer/Vault/vault.service /etc/systemd/system/
    when: gitPullResult|changed
    sudo: yes

  - name: set permissions of service file
    file: 
      path: /etc/systemd/system/vault.service
      mode: 0664 
    sudo: yes

  - name: restart vault server
    systemd:
      name: vault.service
      daemon_reload: yes
      enabled: no
      state: restarted
    when: gitPullResult|changed or secretsGenResult|changed
    sudo: yes


  - name: make sure vault server runs
    systemd:
      name: vault.service
      daemon_reload: yes
      enabled: no
      state: started
    sudo: yes

  # Initialize vault #
  ####################
  - name: check if vault was initialized
    file:
      state: directory
      path: /opt/VaultServer/Vault/data/
    register: initCheckResult
    sudo: yes

  - name: initialize vault
    shell: /opt/VaultServer/Vault/vault init
    when: initCheckResult|changed
    register: vault_init_output
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      
  - name: show vault init output
    when: initCheckResult|changed
    debug: var=vault_init_output
