---
- hosts: vaultdevservers
  remote_user: dominic
  connection: ssh

  vars:
    root_token: "{{ root_token }}"

  tasks:
  - name: auth with root token
    command: /opt/VaultServer/Vault/vault auth {{ root_token }}
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
  
  - name: list auth backends
    command: /opt/VaultServer/Vault/vault read sys/auth
    register: enabledAuthBackends 
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"

  - name: enable userpass authentication
    command: /opt/VaultServer/Vault/vault auth-enable userpass
    when: " ( 'userpass' not in enabledAuthBackends.stdout ) "
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    
  - name: create example policy
    command: /opt/VaultServer/Vault/vault policy-write secrets-readonly /opt/VaultServer/Vault/Policies/readPolicy.hcl
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"

  - name: create new user
    command: /opt/VaultServer/Vault/vault write auth/userpass/users/user password=pw policies=secrets-readonly
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
