---
- hosts: vaultdevservers
  remote_user: dominic
  connection: ssh

  vars:
    local_home: "{{ lookup('env','HOME') }}"

  tasks:
  - name: install git
    apt:
      pkg: git
      update_cache: yes
      state: latest
    sudo: yes
    register: gitInstallResult
    ignore_errors: True

  - name: get repo from github
    git:
      repo: https://github.com/DominicSina/VaultServer.git
      dest: /home/dominic/VaultServer
      version: improvedAnsibleScript
      update: yes
      force: yes
    register: gitPullResult
    ignore_errors: True #is possible update part of deployment?

  - name: make sure secrets folder exists
    file:
      state: directory
      path: /home/dominic/VaultServer/Vault/Secrets
    when: gitPullResult|changed

  - name: create ca
    command: openssl req -newkey rsa:2048 -keyout /home/dominic/VaultServer/Vault/Secrets/privkey.pem -days 3650 -x509 -nodes -out /home/dominic/VaultServer/Vault/Secrets/root.cer -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=DevCA"

  - name: create csr
    command: openssl req -newkey rsa:1024 -nodes -out /home/dominic/VaultServer/Vault/Secrets/vault.csr -keyout /home/dominic/VaultServer/Vault/Secrets/vault.key -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=DevCA"

  - name: create crt
    command: openssl ca -batch -config /home/dominic/VaultServer/Vault/TLS/vault-ca.conf -notext -in /home/dominic/VaultServer/Vault/Secrets/vault.csr -out /home/dominic/VaultServer/Vault/Secrets/vault.crt

  # Only available to a registered user, not useful for following ansible shell module.
  # Still nice to have for local debugging on the target machines.
  - name: add vault binary to PATH in bashrc 
    lineinfile:
      dest: ~/.bashrc
      line: 'export PATH="$PATH:$HOME/VaultServer/Vault" # Adds vault binary to PATH'

  # Similar to task above. Specifies to access local vault server through http using bash.
  - name: add local vault server address in bashrc
    lineinfile:
      dest: ~/.bashrc
      line: 'export VAULT_ADDR="http://127.0.0.1:8200" # Adds local vault server address to bash'

  # Memlock is needed for vault in linux systems. Vault needs memlock capabilites when
  # nonencrypted swaps are performed https://www.vaultproject.io/docs/configuration/index.html
  - capabilities: 
      path: /home/dominic/VaultServer/Vault/vault
      capability: cap_ipc_lock=+ep
      state: present
    sudo: yes

  - name: copy service file
    command: cp /home/dominic/VaultServer/Vault/vault.service /etc/systemd/system/
    sudo: yes

  - name: set permissions of service file
    command: chmod 664 /etc/systemd/system/vault.service
    sudo: yes

  - name: start vault server
    systemd:
      name: vault.service
      daemon_reload: yes
      enabled: no
      state: started
    sudo: yes

  - name: show server output
    debug: var=server_output

  - name: remove previous vault
    file:
      state: absent
      path: /home/dominic/VaultServer/Vault/data/
    sudo: yes

  - name: initialize vault
    shell: /home/dominic/VaultServer/Vault/vault init
    register: vault_init_output
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      
  - name: show vault init output
    debug: var=vault_init_output
